### ISSUE TITLE
Conditional data annotations seem to not work when inputs are named dynamically (BeginCollectionItem HtmlHelper)

### ISSUE THREAD

**Issue by samuelmaxton** [NickBranstein/MvcValidationExtensions#1]
Hello! 
I am attempting to use [RequiredIfValue] and/or [RequiredIfAnyValue] linked to inputs that are named dynamically in the View. I'm using another Nuget Package which provides the dynamic naming => [BeginCollectionItem HtmlHelper] (https://www.nuget.org/packages/BeginCollectionItem/). 

One other detail is that the condition or value I am checking for is of type "bool" (Checkboxes). In other words, ***a textbox should be required only if a specific checkbox is checked***.

**Model:**
***Checkbox***
`[Display(Name = "Is your entry a set?")]`
`public bool? EntrySet { get; set; }`
***Textbox***
`[RequiredIfValue("EntrySet","True")]`
`[RegularExpression("([1-9][0-9]*)", ErrorMessage = "Invalid")]`
`[Range(0, 99, ErrorMessage = "Invalid")]`
`public int? PiecesInSet { get; set; }`

**View:**
***This View can have one or more Entry Forms, and each Entry Form can have one or more Entries. Therefore we use the BeginCollectionItem HtmlHelper so that each input has a unique name.***
    
***Entry Forms***

    @using (Html.BeginCollectionItem("EntryForms"))
    {
        foreach (HeritageArtsEntry ev in Model.HeritageArtsEntries)
         {
              Html.RenderPartial("_HeritageArtsEntry", ev);
         }
    }

***Entries inside each Entry Form***

    @{
            var Contact1Prefix = ViewData.TemplateInfo.HtmlFieldPrefix;
        }

    @using (Html.BeginCollectionItem(Contact1Prefix + ".HeritageArtsEntries"))
    {
        <div class="form-group col-md-2">
            @Html.Bootstrap().CheckBoxFor(ev => ev.EntrySet).HtmlAttributes(new { @class = "form-control colored-blue" }).IsChecked(false)
        </div>
        @Html.Bootstrap().LabelFor(ev => ev.PiecesInSet).LabelText("Number of pieces in your set:").HtmlAttributes(new { @class = "col-md-2 control-label" })
        <div class="form-group col-md-1">
            @Html.Bootstrap().TextBoxFor(ev => ev.PiecesInSet).HtmlAttributes(new { @class = "form-control" }).Placeholder("Enter #")
            @Html.ValidationMessageFor(ev => ev.PiecesInSet)
        </div>
    }

**Actual Rendered Elements in DOM:**

***Checkbox***

    <input class="form-control colored-blue" id="EntryForms_921a053e-b41d-4aef-a0f8-adeee2e9a9a0__HeritageArtsEntries_0b185b02-15dc-490d-8cc3-14dbb5da9e17__EntrySet" name="EntryForms[921a053e-b41d-4aef-a0f8-adeee2e9a9a0].HeritageArtsEntries[0b185b02-15dc-490d-8cc3-14dbb5da9e17].EntrySet" type="checkbox" value="true">

***Textbox***

    <input class="form-control" data-val="true" data-val-number="The field PiecesInSet must be a number." data-val-range="Invalid" data-val-range-max="99" data-val-range-min="0" data-val-regex="Invalid" data-val-regex-pattern="([1-9][0-9]*)" data-val-requiredifvalue="The PiecesInSet field is required." data-val-requiredifvalue-otherproperty="EntrySet" data-val-requiredifvalue-othervalue="True" id="EntryForms_4e70c3cb-7ec6-478c-9549-41fdb0ef99bd__HeritageArtsEntries_32dcac53-24ab-4118-9a9f-f0162b33f386__PiecesInSet" name="EntryForms[4e70c3cb-7ec6-478c-9549-41fdb0ef99bd].HeritageArtsEntries[32dcac53-24ab-4118-9a9f-f0162b33f386].PiecesInSet" placeholder="Enter #" type="text" value="">

In my mind the problem is there is a conflict in ***naming***?

`"EntrySet"` 
is not equal to
`"EntryForms[921a053e-b41d-4aef-a0f8-adeee2e9a9a0].HeritageArtsEntries[0b185b02-15dc-490d-8cc3-14dbb5da9e17].EntrySet"`

If this is a problem it would be a life-saving update and a very useful one I believe! Thanks!
Sam Thompson

**Comment by mikebranstein** [comment]
Interesting problem. Can't wait to dig into it. Thanks for the example, @samuelmaxton

**Comment by NickBranstein** [comment]
Thank you @samuelmaxton.

You are correct in that the issue is with the naming but it isn't really a bug in the code.  Unfortunately this is because of how the MVC engine works and how the extensions were written (by implementing IClientValidatable).  At the time that the client validation rules are generated inside of the MVC engine, the model does not and cannot know that it is part of a collection.

I may look to creating a custom model metadata provider in future implementations where I may have access to more information about the model but this will not be a quick change.

In the mean time there is a potential work around that you could implement which would be to override the client side validation method for this model by updating it on your page load.

```javascript
$(function () {
       $.validator.methods.
});

function newValidation(element, params)
{
                var obj = $(element);
                var otherObj = getObjectFromElement(params.element); // You will want to change this line with a new selector for getting the closest input that is a checkbox.

                if (otherObj.val() == null || otherObj.val() == undefined || otherObj.val() === '') {
                    return true;
                }

                return params.othervalue === otherObj.val() ?
                    obj.val() != null && obj.val() != undefined && obj.val() !== '' : true;
}
```

I hope this help at least provide you with a work around.  Let me know if you have any more questions.

As an aside this is something I will get updated in the documentation because this issue is not unique to this scenario but to any complex model.  In the case of a complex model the work around is to name the other property the full complex model name i.e. (EntityForms.HeritageArtEntry).

**Comment by samuelmaxton** [comment]
Thanks, Nick. Really appreciate you looking at this. I would just like to confirm one line of code above:

       $.validator.methods.requiredif = newValidation;

I was under the impression I should use ***requiredifvalue*** instead of ***requiredif*** since the value of the checkbox must be "True" -------> `[RequiredIfValue("EntrySet","True")]`

       $.validator.methods.requiredifvalue = newValidation;

Is this correct?

**Comment by samuelmaxton** [comment]
Greetings, So I got it working...**Thanks for your help.**

    var newValidation = function (element, params) {
        var obj = $(element);

        //The checkbox's old name
        var otherProperty = $(element).attr("data-val-requiredifvalue-otherproperty");

        //Find the GUID that uniquely identifies the entry I'm working with
        var entryGUID = $(element).parent().parent().parent().parent().find('input').val();
        //Find the relevant checkbox element using its new name
        var otherObj = $('input[name$="[' + entryGUID + '].' + otherProperty + '"]');

        if (otherObj.val() == null || otherObj.val() == undefined || otherObj.val() === '') {
            return true;
        }

        return params.othervalue === otherObj.val() ?
            obj.val() != null && obj.val() != undefined && obj.val() !== '' : true;
    };

    var newValidationMethod = function (value, element, params) {
        return newValidation(element, params);
    };

    $(function () {
        $.validator.methods.requiredifvalue = newValidationMethod;
    });

**Comment by NickBranstein** [comment]
Great I'm glad you were able to get it working!  For the record I think you can used required if as well.  I think the way I implemented it, it is able to determine if checkboxes or radio buttons are checked.
