### ISSUE TITLE
Activate Required attribute when another property IS NULL

### ISSUE THREAD

**Issue by samuelmaxton** [NickBranstein/MvcValidationExtensions#2]
Hey Guys!

Long time. I've run into trouble using the **RequiredIfValue** attribute. By default it activates when the "other" field _IS NOT NULL_. How to make this work if I want the exact opposite, that is, I would like the required attribute to activate when the "other" field _IS NULL_. I have tried the following but no dice so far:

`[RequiredIfValue("DocumentId", "")]`
`[RequiredIfValue("DocumentId", null)]`

Any ideas? 

Thanks,
Sam Thompson
Asheville, NC

**Comment by NickBranstein** [comment]
Sam,

Unfortunately RequiredIfValue was written to intend an actual value to be added (an empty string isn't considered a value) so that is why it is not working.

I will add in a RequiredIfEmpty and push out an update later today for you to use.
